package de.trustable.ca3s.challenge.exception;

public class ChallengeValidationFailedException extends Exception {
}
